/**
 * Bakes the public GitHub repo list into a TS module at build time.
 *
 * Doing this at build time rather than in the browser avoids the 60 req/hr
 * unauthenticated rate limit hitting visitors, plus a loading state and CORS.
 *
 * Refresh with: npm run assets:repos
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const USER = 'Viktor-Nedev';
/** The portfolio repo itself should not appear in its own project list. */
const EXCLUDE = new Set(['Viktor_Nedev']);

interface ApiRepo {
  name: string;
  description: string | null;
  language: string | null;
  homepage: string | null;
  html_url: string;
  stargazers_count: number;
  pushed_at: string;
  fork: boolean;
  archived: boolean;
}

async function main() {
  const res = await fetch(
    `https://api.github.com/users/${USER}/repos?per_page=100&sort=pushed`,
    { headers: { Accept: 'application/vnd.github+json', 'User-Agent': USER } },
  );
  if (!res.ok) throw new Error(`GitHub API ${res.status} ${res.statusText}`);

  const raw = (await res.json()) as ApiRepo[];
  const repos = raw
    .filter((r) => !r.fork && !r.archived && !EXCLUDE.has(r.name))
    .map((r) => ({
      name: r.name,
      description: r.description,
      language: r.language,
      homepage: r.homepage && r.homepage.trim() ? r.homepage.trim() : null,
      url: r.html_url,
      stars: r.stargazers_count,
      pushedAt: r.pushed_at.slice(0, 10),
    }));

  const file = `// Generated by scripts/fetch-repos.mts - do not edit by hand.
import type { Repo } from './types';

export const repos: Repo[] = ${JSON.stringify(repos, null, 2)};
`;
  await writeFile(path.join(ROOT, 'src/data/repos.generated.ts'), file, 'utf8');

  const withDemo = repos.filter((r) => r.homepage).length;
  console.log(`Wrote ${repos.length} repos (${withDemo} with live demos).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
