// Generated by scripts/prepare-media.mts - do not edit by hand.

/** Blur placeholders for each clip's poster frame. */
export const posterLqip: Record<string, string> = {
  "hero-forest": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAwCdASoYAA4ALrV2u12jqampiYC0SxgE6AIfDkSUusZsscdLPIAAAP7niGceX3ofmPRxXeNrC0YLeSp6ivHH9SPXbc/kqaBAAA=="
};
