// Generated by scripts/fetch-repos.mts - do not edit by hand.
import type { Repo } from './types';

export const repos: Repo[] = [
  {
    "name": "Viktor",
    "description": null,
    "language": null,
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Viktor",
    "stars": 0,
    "pushedAt": "2026-09-01"
  },
  {
    "name": "Huddle",
    "description": "Huddle — an AI form coach and pickup-game finder in one PWA. Check your exercise form with your webcam, find a local game, and earn badges for staying active together. Built for PeddieHacks 2026.",
    "language": "TypeScript",
    "homepage": "https://huddle-indol-phi.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Huddle",
    "stars": 0,
    "pushedAt": "2026-08-15"
  },
  {
    "name": "lucid",
    "description": null,
    "language": "TypeScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/lucid",
    "stars": 0,
    "pushedAt": "2026-08-13"
  },
  {
    "name": "Hearsay",
    "description": null,
    "language": "Python",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Hearsay",
    "stars": 0,
    "pushedAt": "2026-08-12"
  },
  {
    "name": "Freshly",
    "description": null,
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Freshly",
    "stars": 0,
    "pushedAt": "2026-08-09"
  },
  {
    "name": "youtube",
    "description": null,
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/youtube",
    "stars": 0,
    "pushedAt": "2026-08-07"
  },
  {
    "name": "youtube_hackathon",
    "description": null,
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/youtube_hackathon",
    "stars": 0,
    "pushedAt": "2026-08-04"
  },
  {
    "name": "chorus",
    "description": null,
    "language": "JavaScript",
    "homepage": "https://chorus-wheat.vercel.app",
    "url": "https://github.com/Viktor-Nedev/chorus",
    "stars": 0,
    "pushedAt": "2026-08-01"
  },
  {
    "name": "Segpilot",
    "description": null,
    "language": "Python",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Segpilot",
    "stars": 0,
    "pushedAt": "2026-07-29"
  },
  {
    "name": "daybot",
    "description": null,
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/daybot",
    "stars": 0,
    "pushedAt": "2026-07-12"
  },
  {
    "name": "SmartCity",
    "description": "School practice 2026",
    "language": "Dart",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/SmartCity",
    "stars": 0,
    "pushedAt": "2026-07-10"
  },
  {
    "name": "Maharashtra",
    "description": null,
    "language": "TypeScript",
    "homepage": "https://maharashtra-kappa.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Maharashtra",
    "stars": 0,
    "pushedAt": "2026-07-01"
  },
  {
    "name": "Genza",
    "description": null,
    "language": "TypeScript",
    "homepage": "https://genza-five.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Genza",
    "stars": 0,
    "pushedAt": "2026-06-14"
  },
  {
    "name": "Finova",
    "description": null,
    "language": "TypeScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Finova",
    "stars": 0,
    "pushedAt": "2026-05-27"
  },
  {
    "name": "Nourish",
    "description": null,
    "language": "Jac",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Nourish",
    "stars": 0,
    "pushedAt": "2026-05-19"
  },
  {
    "name": "misterygame",
    "description": null,
    "language": "JavaScript",
    "homepage": "https://misterygame-flax.vercel.app",
    "url": "https://github.com/Viktor-Nedev/misterygame",
    "stars": 0,
    "pushedAt": "2026-05-10"
  },
  {
    "name": "Briefly",
    "description": null,
    "language": "TypeScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Briefly",
    "stars": 0,
    "pushedAt": "2026-05-08"
  },
  {
    "name": "Helion",
    "description": null,
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Helion",
    "stars": 0,
    "pushedAt": "2026-05-01"
  },
  {
    "name": "adora",
    "description": null,
    "language": "TypeScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/adora",
    "stars": 0,
    "pushedAt": "2026-04-27"
  },
  {
    "name": "Cognix",
    "description": null,
    "language": "JavaScript",
    "homepage": "https://cognix-omega.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Cognix",
    "stars": 0,
    "pushedAt": "2026-04-19"
  },
  {
    "name": "hireon",
    "description": null,
    "language": "TypeScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/hireon",
    "stars": 0,
    "pushedAt": "2026-04-12"
  },
  {
    "name": "Animatch",
    "description": "Проект за SoftUni - ASP.NET модул",
    "language": "C#",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Animatch",
    "stars": 0,
    "pushedAt": "2026-04-07"
  },
  {
    "name": "Crazy_Golf",
    "description": null,
    "language": "JavaScript",
    "homepage": "https://minigolf-blue.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Crazy_Golf",
    "stars": 0,
    "pushedAt": "2026-03-29"
  },
  {
    "name": "Grabme",
    "description": null,
    "language": "TypeScript",
    "homepage": "https://grabme-bay.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Grabme",
    "stars": 0,
    "pushedAt": "2026-03-23"
  },
  {
    "name": "Gexe",
    "description": null,
    "language": "JavaScript",
    "homepage": "https://gexe.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Gexe",
    "stars": 0,
    "pushedAt": "2026-03-13"
  },
  {
    "name": "Transcriptio",
    "description": "An offline AI translator that runs on-device using Melange AI models.",
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Transcriptio",
    "stars": 0,
    "pushedAt": "2026-03-11"
  },
  {
    "name": "Fridgeo",
    "description": "Highly visual recipe-finding app",
    "language": "Svelte",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Fridgeo",
    "stars": 0,
    "pushedAt": "2026-03-07"
  },
  {
    "name": "Domus",
    "description": "AI-powered platform connecting displaced families with safe housing, humanitarian support, and a path to rebuild their lives.",
    "language": "TypeScript",
    "homepage": "https://domus-seven-pi.vercel.app",
    "url": "https://github.com/Viktor-Nedev/Domus",
    "stars": 0,
    "pushedAt": "2026-03-02"
  },
  {
    "name": "zoodle_sait",
    "description": null,
    "language": "HTML",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/zoodle_sait",
    "stars": 0,
    "pushedAt": "2026-03-01"
  },
  {
    "name": "Zoodle",
    "description": null,
    "language": "Dart",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Zoodle",
    "stars": 0,
    "pushedAt": "2026-03-01"
  },
  {
    "name": "Claryx",
    "description": "Assistive tools for visual, motor, and cognitive accessibility — all in one place.",
    "language": "TypeScript",
    "homepage": "https://claryx-9src.vercel.app/",
    "url": "https://github.com/Viktor-Nedev/Claryx",
    "stars": 0,
    "pushedAt": "2026-02-22"
  },
  {
    "name": "Claryx_Beta",
    "description": "Web system for people with disabilities",
    "language": "JavaScript",
    "homepage": null,
    "url": "https://github.com/Viktor-Nedev/Claryx_Beta",
    "stars": 0,
    "pushedAt": "2026-02-21"
  },
  {
    "name": "WhenPigsFly",
    "description": "Game for Oink Game Jam",
    "language": "TypeScript",
    "homepage": "https://when-pigs-fly.vercel.app",
    "url": "https://github.com/Viktor-Nedev/WhenPigsFly",
    "stars": 0,
    "pushedAt": "2026-02-09"
  },
  {
    "name": "ELIA",
    "description": "Environmental Lifecycle Intelligence Assistant",
    "language": "TypeScript",
    "homepage": "https://elia-theta.vercel.app",
    "url": "https://github.com/Viktor-Nedev/ELIA",
    "stars": 0,
    "pushedAt": "2026-02-01"
  }
];
